sudo: required
services:
  - docker

before_install:
  - docker build  -t jason/docker-react -f Dockerfile.dev .

script:
  # hang without -- --coverage, waiting for more input after test
  - docker run jason/docker-react npm run test -- --coverage
